### ISSUE TITLE
Windows only application

### ISSUE THREAD

**Issue by jayantrane** [Stewart86/roadtaxTracker#36]
I was not able to run this project on MacOS. Got this error while running app.

`(roadtaxTracker)  roadtaxTracker % python RoadTaxTracker.py
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
Traceback (most recent call last):
  File "RoadTaxTracker.py", line 2, in <module>
    import view
  File "/Users/_PATH_/roadtaxTracker/view.py", line 28, in <module>
    ctypes.windll.shcore.SetProcessDpiAwareness(1)
AttributeError: module 'ctypes' has no attribute 'windll'`

This error is explained here [https://stackoverflow.com/questions/63533869/module-ctypes-has-no-attribute-windll](url)

Should we update the README file with OS this project is supported on?

**Comment by jayantrane** [comment]
@Stewart86 Any thoughs?
